AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 150

