require:
  - "rubocop-rake"
  - "rubocop-rspec"

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/*'

RSpec/MessageSpies:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 150

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
